spring:
  application:
    name: hotelService
  datasource:
    url: jdbc:postgresql://34.93.233.58:5432/cmsrdev?autoReconnect=true&useSSL=false
    username: postgres
    password: isu12345
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
server:
  port: 7172
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7070/eureka
  instance:
    prefer-ip-address: true